# Generated by Django 4.2.7 on 2023-12-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_person_options_alter_person_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthDay',
            field=models.DateField(default='2020-01-01', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='Гендер'),
        ),
    ]
