# Generated by Django 4.2.7 on 2023-12-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_gender_alter_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
